version: '3.8'

services:
  # Serviço da API FastAPI
  api:
    build: .
    container_name: gestao_escolar_api
    ports:
      - "8000:8000"
    volumes:
      # Monta o código local no contêiner.
      # Isso permite que as alterações no código sejam refletidas sem precisar reconstruir a imagem.
      - .:/app